#02_01 Array types and conversions between types

In [5]:
import numpy as np
integers = np.array([10,20,30,40,50])
print(integers)

[10 20 30 40 50]


In [7]:
integers[0]

np.int64(10)

In [10]:
integers[0]=20
integers

array([20, 20, 30, 40, 50])

In [13]:
integers[0]=21.5
integers

array([21, 20, 30, 40, 50])

In [15]:
integers.dtype

dtype('int64')

In [17]:
smallerIntegers=np.array(integers, dtype=np.int8)
smallerIntegers

array([21, 20, 30, 40, 50], dtype=int8)

In [19]:
integers.nbytes

40

In [22]:
smallerIntegers.nbytes

5

In [24]:
overflow = np.array([127, 128, 129], dtype = np.int8)
overflow

OverflowError: Python integer 128 out of bounds for int8

In [27]:
floats=np.array([1.2,2.3,3.4,5.1,8.3])
print(floats)

[1.2 2.3 3.4 5.1 8.3]


In [29]:
floats.dtype

dtype('float64')