Finding he shape and size of an array

In [1]:
import numpy as np

In [6]:
first_arr=np.arange(20)
first_arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [9]:
second_arr=np.linspace((1,2),(10,20),10)
second_arr

array([[ 1.,  2.],
       [ 2.,  4.],
       [ 3.,  6.],
       [ 4.,  8.],
       [ 5., 10.],
       [ 6., 12.],
       [ 7., 14.],
       [ 8., 16.],
       [ 9., 18.],
       [10., 20.]])

In [11]:
third_arr=np.full((2,2,2),10)
third_arr

array([[[10, 10],
        [10, 10]],

       [[10, 10],
        [10, 10]]])

In [13]:
np.shape(first_arr)

(20,)

In [15]:
np.shape(second_arr)

(10, 2)

In [18]:
np.shape(third_arr)

(2, 2, 2)

In [20]:
np.size(first_arr)

20

In [22]:
np.size(second_arr)

20

In [23]:
np.size(third_arr)

8