Creating arrays from lists and Python structures

In [2]:
import numpy as np

In [6]:
first_list=[1,2,3,4,5,6,7,8,9,10]
print(first_list)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [8]:
first_array=np.array(first_list)
first_list

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [10]:
second_list=[1,2,3,-1.23,50,1280000.56,4.56]
second_array=np.array(second_list)
print(second_array)

[ 1.00000000e+00  2.00000000e+00  3.00000000e+00 -1.23000000e+00
  5.00000000e+01  1.28000056e+06  4.56000000e+00]


In [12]:
second_array.dtype

dtype('float64')

In [14]:
third_list=['Ann',11111,'peter',11112,'Susan',111113, 'John', 11114]
third_array=np.array(third_list)
third_array

array(['Ann', '11111', 'peter', '11112', 'Susan', '111113', 'John',
       '11114'], dtype='<U21')

In [16]:
first_tuple=(5,10,15,20,25,30)
array_from_tuple=np.array(first_tuple)
print(array_from_tuple)

[ 5 10 15 20 25 30]


In [18]:
array_from_tuple.dtype

dtype('int64')

In [39]:
multi_dim_list=[
    [
        [   
            [
                [0,1,2],
                [3,4,5]
            ]
            ,[
                [0,1,2],
                [3,4,5]
            ]
        ],
        [
            [
                [0,1,2],
                [3,4,5]
            ]
            ,[
                [0,1,2],
                [3,4,5]
            ]
        ]
    ],
    [
        [
            [
                [0,1,2],
                [3,4,5]
            ]
            ,[
                [0,1,2],
                [3,4,5]
            ]
        ],
        [
            [
                [0,1,2],
                [3,4,5]
            ]
            ,[
                [0,1,2],
                [3,4,5]
            ]
        ]
    ],
]
arr_from_multi_dim_list=np.array(multi_dim_list)
print(arr_from_multi_dim_list)

[[[[[0 1 2]
    [3 4 5]]

   [[0 1 2]
    [3 4 5]]]


  [[[0 1 2]
    [3 4 5]]

   [[0 1 2]
    [3 4 5]]]]



 [[[[0 1 2]
    [3 4 5]]

   [[0 1 2]
    [3 4 5]]]


  [[[0 1 2]
    [3 4 5]]

   [[0 1 2]
    [3 4 5]]]]]


In [40]:
arr_from_multi_dim_list.ndim

5