Adding, removing and sorting elements

In [2]:
import numpy as np

In [43]:
first_arr=np.array([1,2,3,5])
print('Array')
print(first_arr)
new_first_arr=np.insert(first_arr,3,4)
print('Insert')
print(new_first_arr)

Array
[1 2 3 5]
Insert
[1 2 3 4 5]


In [39]:
second_arr=np.array([1,2,3,4])
print('Array')
print(second_arr)
new_second_arr=np.append(second_arr,5)
print('Element appended')
print(new_second_arr)

Array
[1 2 3 4]
Element appended
[1 2 3 4 5]


In [37]:
third_arr=np.array([1,2,3,4,5,6])
print('Array')
print(third_arr)
del_arr=np.delete(third_arr,5)
print('Element 5 deleted')
print(del_arr)

Array
[1 2 3 4 5 6]
Element 5 deleted
[1 2 3 4 5]


In [34]:
integers_arr=np.random.randint(0,20,20)
print('Unsorted array')
print(integers_arr)
print('Sorted Array')
print(np.sort(integers_arr))

Unsorted array
[18  4  3  3 19  8 15 17 17  4 16 18  9 18 17 18 18  3 15 16]
Sorted Array
[ 3  3  3  4  4  8  9 15 15 16 16 17 17 17 18 18 18 18 18 19]


In [33]:
integers_2dim_arr=np.array([[3,2,5,7,4],[5,0,8,3,1]])
print('Unsorted 2D Array')
print(integers_2dim_arr)
print('Sorted 2D Array')
print(np.sort(integers_2dim_arr))

Unsorted 2D Array
[[3 2 5 7 4]
 [5 0 8 3 1]]
Sorted 2D Array
[[2 3 4 5 7]
 [0 1 3 5 8]]


In [ ]:
second_arr=np.linspace((1,2),(10,20),10)
second_arr

array([[ 1.,  2.],
       [ 2.,  4.],
       [ 3.,  6.],
       [ 4.,  8.],
       [ 5., 10.],
       [ 6., 12.],
       [ 7., 14.],
       [ 8., 16.],
       [ 9., 18.],
       [10., 20.]])

In [28]:
colors=np.array(['orange','green','yellow','white','black','pink','blue','red'])
print(colors)
print(np.sort(colors))

['orange' 'green' 'yellow' 'white' 'black' 'pink' 'blue' 'red']
['black' 'blue' 'green' 'orange' 'pink' 'red' 'white' 'yellow']
