Indexing and slicing

In [1]:
import numpy as np

In [4]:
twodim_arr=np.reshape(np.arange(12),(3,4))
twodim_arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [8]:
twodim_arr[1,1]
twodim_arr[1]

array([4, 5, 6, 7])

In [10]:
threedim_arr=np.reshape(np.arange(3*4*5),(3,4,5))
threedim_arr

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39]],

       [[40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59]]])

In [12]:
threedim_arr[0,2,3]

np.int64(13)

In [15]:
threedim_arr[2,-1,1]

np.int64(56)

In [17]:
onedim_arr=np.arange(10)
onedim_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
onedim_arr[2:6]

array([2, 3, 4, 5])

In [21]:
onedim_arr[:5]

array([0, 1, 2, 3, 4])

In [25]:
onedim_arr[-3:]

array([7, 8, 9])

In [28]:
onedim_arr[::3]

array([0, 3, 6, 9])

In [30]:
twodim_arr[1:,1:]

array([[ 5,  6,  7],
       [ 9, 10, 11]])

In [32]:
twodim_arr[1,:]

array([4, 5, 6, 7])

In [33]:
twodim_arr[:,2]

array([ 2,  6, 10])