# Transposition for the Matrix Product

We saw that:

- the **dot product** of two vectors gives a single number (scalar)
- the **matrix product** of a row vector and a column vector also gives a
  single value in a $(1,1)$ matrix

These are really the *same* operation in disguise.

If $\mathbf{a}$ and $\mathbf{b}$ are vectors of length $n$:

- dot product:

$$
\mathbf{a} \cdot \mathbf{b}
= \sum_{i=1}^{n} a_i b_i
$$

- matrix view:

  - turn $\mathbf{a}$ into a **row vector** (shape $(1, n)$)
  - turn $\mathbf{b}$ into a **column vector** (shape $(n, 1)$)
  - their matrix product has shape $(1, 1)$ and stores the same value

To get from a row vector to a column vector (or vice versa),
we use **transposition**.


In [1]:
import numpy as np

a = [1, 2, 3]
b = [2, 3, 4]

# Plain dot product of 1D vectors
dot_vec = np.dot(a, b)

# Turn a into a row vector (1, 3)
a_row = np.array([a])

# Turn b into a column vector (3, 1) via transpose
b_col = np.array([b]).T

dot_mat = np.dot(a_row, b_col)

print("Dot product (1D vectors):", dot_vec)
print("Row vector shape:", a_row.shape)
print("Column vector shape:", b_col.shape)
print("Matrix product (row x column):\n", dot_mat)
print("Matrix product shape:", dot_mat.shape)

Dot product (1D vectors): 20
Row vector shape: (1, 3)
Column vector shape: (3, 1)
Matrix product (row x column):
 [[20]]
Matrix product shape: (1, 1)


## What Is Transposition?

Transposition flips a matrix so that:

- rows become columns
- columns become rows

If an array has shape $(m, n)$, then its transpose has shape $(n, m)$.

In NumPy, the transpose of an array `A` is written `A.T`.


In [2]:
M = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print("M:\n", M)
print("Shape of M:", M.shape)

M_T = M.T

print("\nM.T:\n", M_T)
print("Shape of M.T:", M_T.shape)

M:
 [[1 2 3]
 [4 5 6]]
Shape of M: (2, 3)

M.T:
 [[1 4]
 [2 5]
 [3 6]]
Shape of M.T: (3, 2)


## Row Vectors

A **row vector** is a matrix with:

- 1 row,
- $n$ columns.

Shape: $(1, n)$.

Examples with 3 elements:

```python
np.array([[1, 2, 3]])      # explicit 2D row
np.array([a])              # if a = [1, 2, 3]
np.expand_dims(np.array(a), axis=0)
```

All of these create a $(1, 3)$ array.


In [3]:
a = [1, 2, 3]

row1 = np.array([[1, 2, 3]])
row2 = np.array([a])
row3 = np.expand_dims(np.array(a), axis=0)

print("row1:\n", row1, "shape:", row1.shape)
print("row2:\n", row2, "shape:", row2.shape)
print("row3:\n", row3, "shape:", row3.shape)

row1:
 [[1 2 3]] shape: (1, 3)
row2:
 [[1 2 3]] shape: (1, 3)
row3:
 [[1 2 3]] shape: (1, 3)


## Column Vectors

A **column vector** is a matrix with:

- $n$ rows,
- 1 column.

Shape: $(n, 1)$.

We can get a column vector by transposing a row vector:

```python
row = np.array([[1, 2, 3]])  # shape (1, 3)
col = row.T                  # shape (3, 1)
```

Or, starting from a 1D vector `b = [2, 3, 4]`, we can do:

```python
np.array([b]).T  # shape (3, 1)
```


In [4]:
b = [2, 3, 4]

row_b = np.array([b])   # (1, 3)
col_b = row_b.T         # (3, 1)

print("Row version:\n", row_b, "shape:", row_b.shape)
print("Column version:\n", col_b, "shape:", col_b.shape)

Row version:
 [[2 3 4]] shape: (1, 3)
Column version:
 [[2]
 [3]
 [4]] shape: (3, 1)


## Dot Product as Matrix Product (Summary)

To express the dot product as a matrix product:

1. Start with two 1D vectors `a` and `b`
2. Turn `a` into a **row vector**: shape $(1, n)$
3. Turn `b` into a **column vector**: shape $(n, 1)$
4. Perform the matrix product:

   $$
   (1, n) \times (n, 1) \rightarrow (1, 1)
   $$

The single value inside the $(1,1)$ result is the same as the dot product
of the original 1D vectors.

In NumPy, we used:

```python
a = np.array([a])       # row vector
b = np.array([b]).T     # column vector
np.dot(a, b)            # matrix product -> (1, 1)
```

So:

- **transpose** lets us switch between row and column views,
- **matrix product** over row/column vectors matches the familiar dot product.
