Creating arrays filled with constant values

In [1]:
import numpy as np

In [4]:
first_z_array =np.zeros(5)
first_z_array

array([0., 0., 0., 0., 0.])

In [6]:
second_z_array=np.zeros((4,5))
second_z_array

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [8]:
first_one_array = np.ones(6)
first_one_array

array([1., 1., 1., 1., 1., 1.])

In [10]:
second_ones_array = np.ones((7,1))
second_ones_array

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.]])

In [12]:
third_ones_array=np.ones((4,5),dtype=int)
third_ones_array

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [15]:
first_fill_array = np.empty(10,dtype=int)
first_fill_array.fill(12)
first_fill_array


array([12, 12, 12, 12, 12, 12, 12, 12, 12, 12])

In [17]:
first_full_array=np.full(5,10)
first_full_array

array([10, 10, 10, 10, 10])

In [19]:
second_full_array=np.full((4,5),8)
second_full_array

array([[8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8]])