Intrisic NumPy array creation

In [1]:
import numpy as np

In [5]:
integers_array=np.arange(10)
print(integers_array)

[0 1 2 3 4 5 6 7 8 9]


In [8]:
integers_second_array=np.arange(100,130)
print(integers_second_array)

[100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117
 118 119 120 121 122 123 124 125 126 127 128 129]


In [10]:
integers_third_array=np.arange(100, 151,2)
print(integers_third_array)

[100 102 104 106 108 110 112 114 116 118 120 122 124 126 128 130 132 134
 136 138 140 142 144 146 148 150]


In [12]:
first_floats_arr=np.linspace(10,20)
first_floats_arr

array([10.        , 10.20408163, 10.40816327, 10.6122449 , 10.81632653,
       11.02040816, 11.2244898 , 11.42857143, 11.63265306, 11.83673469,
       12.04081633, 12.24489796, 12.44897959, 12.65306122, 12.85714286,
       13.06122449, 13.26530612, 13.46938776, 13.67346939, 13.87755102,
       14.08163265, 14.28571429, 14.48979592, 14.69387755, 14.89795918,
       15.10204082, 15.30612245, 15.51020408, 15.71428571, 15.91836735,
       16.12244898, 16.32653061, 16.53061224, 16.73469388, 16.93877551,
       17.14285714, 17.34693878, 17.55102041, 17.75510204, 17.95918367,
       18.16326531, 18.36734694, 18.57142857, 18.7755102 , 18.97959184,
       19.18367347, 19.3877551 , 19.59183673, 19.79591837, 20.        ])

In [17]:
second_floats_arr=np.linspace(10,20,5)
print(second_floats_arr)

[10.  12.5 15.  17.5 20. ]


In [23]:
first_rand_arr=np.random.rand(10)
print(first_rand_arr)

[0.36766985 0.69852143 0.18665149 0.35320881 0.50391434 0.34401878
 0.84428314 0.09007109 0.55651887 0.03252207]


In [25]:
second_rand_arr=np.random.rand(4,4)
print(second_rand_arr)

[[0.34928293 0.96938485 0.95743502 0.76534315]
 [0.30182988 0.63694623 0.66142142 0.07762661]
 [0.02757239 0.99920448 0.86744961 0.31782621]
 [0.26590116 0.68813986 0.11462498 0.36637402]]


In [26]:
third_rand_arr = np.random.randint(0,120,20)
third_rand_arr

array([ 85,  52,  76,  73,  44,  10,  65,  91,  97, 109,  65,  73,  10,
       104,  73, 109,  60, 118,  25,  40], dtype=int32)