Copies and Views

In [1]:
import numpy as np

In [5]:
students_ids_number=np.array([1111,1212,1313,1515,1616,1818])
print(students_ids_number)
students_ids_number_reg=students_ids_number
print("id of students_ids_number", id(students_ids_number))
print("id of students_ids_number_reg", id(students_ids_number_reg))

[1111 1212 1313 1515 1616 1818]
id of students_ids_number 3168942029488
id of students_ids_number_reg 3168942029488


In [7]:
students_ids_number_reg[1]=2222
print(students_ids_number)
print(students_ids_number_reg)

[1111 2222 1313 1515 1616 1818]
[1111 2222 1313 1515 1616 1818]


In [9]:
students_ids_number_cp=students_ids_number.copy()
print(students_ids_number_cp)

[1111 2222 1313 1515 1616 1818]


In [11]:
print(students_ids_number_cp==students_ids_number)

[ True  True  True  True  True  True]


In [13]:
print('id of students_id_number',id(students_ids_number))
print('id of students_ids_number_cp',id(students_ids_number_cp))

id of students_id_number 3168942029488
id of students_ids_number_cp 3168963519920


In [16]:
students_ids_number[0]=1000
print('Original: ',students_ids_number)
print('Copy: ', students_ids_number_cp)

Original:  [1000 2222 1313 1515 1616 1818]
Copy:  [1111 2222 1313 1515 1616 1818]


In [21]:
students_ids_number_v=students_ids_number.view()

In [23]:
students_ids_number_v[0] = 2000
print('Original: ',students_ids_number)
print('View: ', students_ids_number_v)

Original:  [2000 2222 1313 1515 1616 1818]
View:  [2000 2222 1313 1515 1616 1818]


In [26]:
print(students_ids_number_cp.base)
print(students_ids_number_v.base)

None
[2000 2222 1313 1515 1616 1818]
