Reversing an array

In [1]:
import numpy as np

In [5]:
arr_one_dim=[10,1,9,2,8,3,7,4,6,5]
arr_one_dim

[10, 1, 9, 2, 8, 3, 7, 4, 6, 5]

In [7]:
arr_one_dim[::-1]

[5, 6, 4, 7, 3, 8, 2, 9, 1, 10]

In [9]:
np.flip(arr_one_dim)

array([ 5,  6,  4,  7,  3,  8,  2,  9,  1, 10])

In [12]:
arr_two_dim=np.arange(9).reshape(3,3)
arr_two_dim

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [14]:
np.flip(arr_two_dim, axis=1)

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

In [16]:
np.flip(arr_two_dim)

array([[8, 7, 6],
       [5, 4, 3],
       [2, 1, 0]])

In [18]:
arr_three_dim=np.arange(24).reshape(2,3,4)
arr_three_dim

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [20]:
np.flip(arr_three_dim, 1)

array([[[ 8,  9, 10, 11],
        [ 4,  5,  6,  7],
        [ 0,  1,  2,  3]],

       [[20, 21, 22, 23],
        [16, 17, 18, 19],
        [12, 13, 14, 15]]])

In [21]:
np.flip(arr_three_dim, 2)

array([[[ 3,  2,  1,  0],
        [ 7,  6,  5,  4],
        [11, 10,  9,  8]],

       [[15, 14, 13, 12],
        [19, 18, 17, 16],
        [23, 22, 21, 20]]])