Aggregate functions

In [1]:
import numpy as np

In [3]:
first_arr=np.arange(10,110,10)
first_arr

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [5]:
second_arr=np.arange(10,100,10).reshape(3,3)
second_arr

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [8]:
third_arr=np.arange(10,110,10).reshape(2,5)
third_arr

array([[ 10,  20,  30,  40,  50],
       [ 60,  70,  80,  90, 100]])

In [10]:
first_arr.sum()

np.int64(550)

In [12]:
second_arr.sum()

np.int64(450)

In [14]:
third_arr.sum()

np.int64(550)

In [16]:
second_arr.sum(axis=0)

array([120, 150, 180])

In [18]:
second_arr.sum(axis=1)

array([ 60, 150, 240])

In [20]:
first_arr.prod()

np.int64(36288000000000000)

In [22]:
second_arr.prod()

np.int64(362880000000000)

In [24]:
third_arr.prod()

np.int64(36288000000000000)

In [26]:
third_arr.prod(axis=0)

array([ 600, 1400, 2400, 3600, 5000])

In [28]:
np.average(first_arr)

np.float64(55.0)

In [30]:
np.average(second_arr)

np.float64(50.0)

In [32]:
np.average(third_arr)

np.float64(55.0)

In [34]:
np.min(first_arr)

np.int64(10)

In [38]:
np.max(first_arr)

np.int64(100)

In [40]:
np.mean(first_arr)

np.float64(55.0)

In [41]:
np.std(first_arr)

np.float64(28.722813232690143)