# NNFS – Chapter 3: Dense Layer Class

In this notebook we follow the **Dense Layer Class** section of *Neural Networks from Scratch*.

Goals:
- Understand what a **dense (fully-connected) layer** is.
- Implement a reusable `Layer_Dense` class with:
  - random weight initialization
  - zero biases
  - a `forward` method that does the dot product + bias.
- Use it to perform a forward pass on the spiral dataset.

In [1]:
import numpy as np
import nnfs
from nnfs.datasets import spiral_data

nnfs.init()  # seed, dtypes, and dot override for reproducibility

np.set_printoptions(precision=5, suppress=True)

## 1. What is a dense (fully-connected) layer?

A **dense layer** (also called *fully-connected* or `fc` layer) is a layer where:

- Every input is connected to **every neuron** in the layer.
- Each connection has a **weight**.
- Each neuron also has a **bias**.

If we have:
- `n_inputs` features coming in, and
- `n_neurons` neurons in the layer,

then the **weight matrix** will have shape `(n_inputs, n_neurons)` and the **bias vector** will
have shape `(1, n_neurons)`.

## 2. Dense layer class skeleton

In [2]:
# Dense layer skeleton (with pass as placeholder)
class Layer_Dense_Skeleton:
    # Layer initialization
    def __init__(self, n_inputs, n_neurons):
        # Initialize weights and biases later
        pass

    # Forward pass
    def forward(self, inputs):
        # Calculate output values from inputs, weights and biases later
        pass

## 3. Weight and bias initialization

We will:
- Initialize **weights** with small random values from a normal (Gaussian) distribution.
- Initialize **biases** to zeros.

Why random weights?
- If all weights started as 0, every neuron in a layer would do the same thing.
- Randomness breaks the symmetry and lets neurons learn different patterns.

Why small values (e.g. multiplied by `0.01`)?
- Very large initial weights can make training unstable or slow.
- Small non-zero values give us a gentle starting point.

### 3.1 Exploring `np.random.randn` and `np.zeros`

In [3]:
print("Random normal array (2 x 5):")
print(np.random.randn(2, 5))

print("\nZeros array with shape (2, 5):")
print(np.zeros((2, 5)))

Random normal array (2 x 5):
[[ 1.76405  0.40016  0.97874  2.24089  1.86756]
 [-0.97728  0.95009 -0.15136 -0.10322  0.4106 ]]

Zeros array with shape (2, 5):
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


### 3.2 Example: initialize weights and biases manually

In [4]:
n_inputs = 2
n_neurons = 4

weights_example = 0.01 * np.random.randn(n_inputs, n_neurons)
biases_example = np.zeros((1, n_neurons))

print("Weights example (shape", weights_example.shape, "):\n", weights_example)
print("\nBiases example (shape", biases_example.shape, "):\n", biases_example)

Weights example (shape (2, 4) ):
 [[ 0.00144  0.01454  0.00761  0.00122]
 [ 0.00444  0.00334  0.01494 -0.00205]]

Biases example (shape (1, 4) ):
 [[0. 0. 0. 0.]]


## 4. Implementing the `Layer_Dense` class

In [5]:
# Dense layer
class Layer_Dense:
    # Layer initialization
    def __init__(self, n_inputs, n_neurons):
        # Initialize weights and biases
        # Shape of weights: (n_inputs, n_neurons)
        # Shape of biases: (1, n_neurons)
        self.weights = 0.01 * np.random.randn(n_inputs, n_neurons)
        self.biases = np.zeros((1, n_neurons))

    # Forward pass
    def forward(self, inputs):
        # Remember inputs for potential later use (e.g. backprop)
        self.inputs = inputs
        # Calculate output values from inputs, weights, and biases
        # inputs: (batch_size, n_inputs)
        # weights: (n_inputs, n_neurons)
        # result: (batch_size, n_neurons)
        self.output = np.dot(inputs, self.weights) + self.biases

## 5. Creating training data with `spiral_data`

We'll create a 2D spiral dataset using `nnfs.datasets.spiral_data`:

- `X` will have shape `(samples * classes, 2)` → 2 features (x₁, x₂).
- `y` will be the class labels (0, 1, 2, ...).

We then feed `X` into our dense layer.

In [6]:
# Create dataset
X, y = spiral_data(samples=100, classes=3)
print("X shape:", X.shape)
print("y shape:", y.shape)

X shape: (300, 2)
y shape: (300,)


## 6. Forward pass through the dense layer

In [7]:
# Create Dense layer with 2 input features and 3 output values
dense1 = Layer_Dense(2, 3)

# Perform a forward pass of our training data through this layer
dense1.forward(X)

print("Output shape:", dense1.output.shape)
print("First 5 outputs:\n", dense1.output[:5])

Output shape: (300, 3)
First 5 outputs:
 [[ 0.       0.       0.     ]
 [-0.00008  0.00003 -0.00006]
 [-0.00007  0.00005  0.00004]
 [-0.00021  0.00005 -0.00035]
 [-0.00024  0.00004 -0.00046]]


## 7. Summary

In this notebook we:
- Reviewed what a **dense/fully-connected** layer is.
- Talked about random weight initialization and zero biases.
- Implemented a reusable `Layer_Dense` class using NumPy.
- Generated a spiral dataset and ran it through our layer.

Each row in `dense1.output` now represents the outputs of the 3 neurons in the layer
for one input sample. Next steps in the book will add **activation functions** on top of
these raw outputs.